// Code generated by "stringer -type JobCommand -trimprefix Cmd"; DO NOT EDIT.

package immich

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CmdStart-0]
	_ = x[CmdPause-1]
	_ = x[CmdResume-2]
	_ = x[CmdEmpty-3]
}

const _JobCommand_name = "StartPauseResumeEmpty"

var _JobCommand_index = [...]uint8{0, 5, 10, 16, 21}

func (i JobCommand) String() string {
	if i < 0 || i >= JobCommand(len(_JobCommand_index)-1) {
		return "JobCommand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JobCommand_name[_JobCommand_index[i]:_JobCommand_index[i+1]]
}
